#' Filter loci that represent secondary SNPs in a genlight \{adegenet\} object
#'
#' SNP datasets generated by DArT include fragments with more than one SNP and record them 
#' separately with the same CloneID (=AlleleID).
#' These multiple SNP loci within a fragment (secondaries) are likely to be linked, 
#' and so you may wish to remove secondaries.
#' This script filters out loci after ordering the genlight object on based on 
#' repeatability, avgPIC in that order (method="best") or at random (method="random")
#'
#' @param x -- name of the genlight object containing the SNP data [required]
#' @param method -- method of selecting SNP locus to retain, best or random [random]
#' @param verbose -- verbosity: 0, silent or fatal errors; 1, begin and end; 2, progress log ; 3, progress and results summary; 5, full report [default 2]
#' @return The reduced genlight, plus a summary
#' @export
#' @author Arthur Georges (Post to \url{https://groups.google.com/d/forum/dartr})
#' @examples
#' result <- gl.report.secondaries(testset.gl)
#' result2 <- gl.filter.secondaries(testset.gl)

# Last amended 3-Feb-19

gl.filter.secondaries <- function(x, method="random", verbose=2) {

# TIDY UP FILE SPECS

  funname <- match.call()[[1]]

# FLAG SCRIPT START

  if (verbose < 0 | verbose > 5){
    cat("  Warning: Parameter 'verbose' must be an integer between 0 [silent] and 5 [full report], set to 2\n")
    verbose <- 2
  }

  if (verbose > 0) {
    cat("Starting",funname,"\n")
  }

# STANDARD ERROR CHECKING
  
  if(class(x)!="genlight") {
    cat("  Fatal Error: genlight object required!\n"); stop("Execution terminated\n")
  }

  # Work around a bug in adegenet if genlight object is created by subsetting
      if (nLoc(x)!=nrow(x@other$loc.metrics)) { stop("The number of rows in the loc.metrics table does not match the number of loci in your genlight object!")  }

  # Set a population if none is specified (such as if the genlight object has been generated manually)
    if (is.null(pop(x)) | is.na(length(pop(x))) | length(pop(x)) <= 0) {
      if (verbose >= 2){ cat("  Population assignments not detected, individuals assigned to a single population labelled 'pop1'\n")}
      pop(x) <- array("pop1",dim = nLoc(x))
      pop(x) <- as.factor(pop(x))
    }

# FUNCTION SPECIFIC ERROR CHECKING

  if (method != "best" && method != "random"){
    cat("    Warning: method must be specified, set to \'random\'\n")
  }

# DO THE JOB

  if (verbose > 2) {cat("  Total number of SNP loci:",nLoc(x),"\n")}
  
# Sort the genlight object on AlleleID (asc), RepAvg (desc), AvgPIC (desc) 
  if (method == "best") {
    if (verbose > 1){cat("  Selecting one SNP per sequence tag based on best RepAvg and AvgPIC\n")}
    loc.order <- order(x@other$loc.metrics$AlleleID,-x@other$loc.metrics$RepAvg,-x@other$loc.metrics$AvgPIC)
    x <- x[, loc.order]
    x@other$loc.metrics <- x@other$loc.metrics[loc.order, ]
  } else {
    if (verbose > 1){cat("  Selecting one SNP per sequence tag at random\n")}
    n <- length(x@other$loc.metrics$AlleleID)
    index <- sample(1:(n+10000),size=n,replace=FALSE)
    x <- x[,order(index)]
    x@other$loc.metrics <- x@other$loc.metrics[order(index), ]
  }
# Extract the clone ID number
  a <- strsplit(as.character(x@other$loc.metrics$AlleleID),"\\|")
  b <- unlist(a)[ c(TRUE,FALSE,FALSE) ]
# Identify and remove secondaries from the genlight object, including the metadata
  x <- x[,duplicated(b)==FALSE]
  x@other$loc.metrics <- x@other$loc.metrics[duplicated(b)==FALSE,]

# Report secondaries from the genlight object
  if (verbose > 2) {
    if (is.na(table(duplicated(b))[2])) { 
      nsec <- 0
    } else {  
      nsec <- table(duplicated(b))[2]
    }
    cat("    Number of secondaries:",nsec,"\n")
    cat("    Number of loci after secondaries removed:",table(duplicated(b))[1],"\n")
  }
  
# FLAG SCRIPT END

  if (verbose > 0) {
    cat("Completed:",funname,"\n")
  }
  #add to history
  nh <- length(x@other$history)
  x@other$history[[nh + 1]] <- match.call()  
  return(x)
}  
