#' Report summary of RepAvg, repeatability averaged over both alleles for each locus in a genlight {adegenet} object
#'
#' SNP datasets generated by DArT have in index, RepAvg, generated by reproducing the data independently for 30% of loci.
#' RepAvg is the proportion of alleles that give a repeatable result, averaged over both alleles for each locus.
#' 
#' A histogram is produced to aid in selecting a threshold.
#'
#' @param x -- name of the genlight object containing the SNP data [required]
#' @param verbose -- verbosity: 0, silent or fatal errors; 1, begin and end; 2, progress log ; 3, progress and results summary; 5, full report [default 3]
#' @return -- Tabulation of repAvg against prospective Thresholds
#' @importFrom graphics hist
#' @export
#' @author Arthur Georges (Post to \url{https://groups.google.com/d/forum/dartr})
#' @examples
#' gl.report.repavg(testset.gl)

# Last amended 3-Aug-19

gl.report.repavg <- function(x,verbose=3) {

# TIDY UP FILE SPECS

  funname <- match.call()[[1]]

# FLAG SCRIPT START

    if (verbose >=1){
      cat("Starting",funname,"\n")
    }

# STANDARD ERROR CHECKING
  
  if(class(x)!="genlight") {
    cat("  Fatal Error: genlight object required!\n"); stop("Execution terminated\n")
  }

  # Work around a bug in adegenet if genlight object is created by subsetting
      if (nLoc(x)!=nrow(x@other$loc.metrics)) { stop("The number of rows in the loc.metrics table does not match the number of loci in your genlight object!")  }

  # Set a population if none is specified (such as if the genlight object has been generated manually)
    if (is.null(pop(x)) | is.na(length(pop(x))) | length(pop(x)) <= 0) {
      cat("  Population assignments not detected, individuals assigned to a single population labelled 'pop1'\n")
      pop(x) <- array("pop1",dim = nInd(x))
      pop(x) <- as.factor(pop(x))
    }

# DO THE JOB

  repAvg <- x@other$loc.metrics$RepAvg
  xlimit <- min(repAvg)
  
  if (verbose >= 3){
    cat("No. of loci =", nLoc(x), "\n")
    cat("No. of individuals =", nInd(x), "\n")
    cat("  Miniumum repeatability: ",round(min(repAvg),2),"\n")
    cat("  Maximum repeatability: ",round(max(repAvg),2),"\n")
    cat("  Mean repeatability: ",round(mean(repAvg),3),"\n\n")
  }
  
  # Determine the loss of loci for a given filter cut-off
  retained <- array(NA,21)
  pc.retained <- array(NA,21)
  filtered <- array(NA,21)
  pc.filtered <- array(NA,21)
  percentile <- array(NA,21)
  for (index in 1:21) {
    i <- (index - 1)/20
    i <- (i - 1)*(1-xlimit) + 1
    percentile[index] <- i
    retained[index] <- length(repAvg[repAvg >= percentile[index]])
    pc.retained[index] <- round(retained[index]*100/nLoc(x),1)
    filtered[index] <- nLoc(x) - retained[index]
    pc.filtered[index] <- 100 - pc.retained[index]
  }
  df <- cbind(percentile,retained,pc.retained,filtered,pc.filtered)
  df <- data.frame(df)
    colnames(df) <- c("Threshold", "Retained", "Percent", "Filtered", "Percent")
  df <- df[order(-df$Threshold),]
  rownames(df) <- NULL
#  if (verbose >= 3){
#    print(df)
#  }
  
  # Plot a histogram of RepAvg
  # Save the prior settings for mfrow, oma, mai and pty, and reassign
  op <- par(mfrow = c(2, 1), oma=c(1,1,1,1), mai=c(0.5,0.5,0.5,0.5),pty="m")
  # Set margins for first plot
  par(mai=c(1,0.5,0.5,0.5))
  
  hist(repAvg, 
         main="Repeatbility by Locus", 
         xlab="Repeatability", 
         border="blue", 
         col="red",
         xlim=c(min(repAvg),1),
         breaks=100)

  # FLAG SCRIPT END
  
  if (verbose > 0) {
    cat("Completed:",funname,"\n")
  }
  
  # Reset the par options    
  par(op)
  
  # Return the result
  return(df)

}


