#' Report loci containing secondary SNPs in a genlight \{adegenet\} object 
#'
#' SNP datasets generated by DArT include fragments with more than one SNP (that is, with secondaries) and record them separately with the same CloneID (=AlleleID).
#' These multiple SNP loci within a fragment are likely to be linked, and so you may wish to remove secondaries.
#'
#' A histogram and or a smearplot can be requested. Note that the smearplot is computationally intensive, and will take time to 
#' execute on large datasets.
#'
#' @param x -- name of the genlight object containing the SNP data [required]
#' @param plot -- if TRUE, will produce a frequency plot the number of SNPs per sequence tag [default = FALSE] 
#' @param smearplot if TRUE, will produce a smearplot of individuals against loci [default FALSE]
#' @return A genlight object of loci with multiple SNP calls
#' @importFrom adegenet glPlot
#' @importFrom graphics barplot
#' @export
#' @author Arthur Georges (Post to \url{https://groups.google.com/d/forum/dartr})
#' @examples
#' gl.report.secondaries(testset.gl)


gl.report.secondaries <- function(x, plot=FALSE, smearplot=FALSE) {

# ERROR CHECKING
  
  if(class(x)!="genlight") {
    cat("Fatal Error: genlight object required for gl.report.repavg!\n"); stop()
  }
  # Work around a bug in adegenet if genlight object is created by subsetting
  x@other$loc.metrics <- x@other$loc.metrics[1:nLoc(x),]
  
# FLAG SCRIPT START
  cat("Starting gl.report.secondaries: Reporting frequency of secondary SNPs within a single sequence tag\n")

# Extract the clone ID number
  a <- strsplit(as.character(x@other$loc.metrics$AlleleID),"\\|")
  b <- unlist(a)[ c(TRUE,FALSE,FALSE) ]
  x.secondaries <- x[,duplicated(b)]
     # Work around a bug in adegenet if genlight object is created by subsetting
     x.secondaries@other$loc.metrics <- x.secondaries@other$loc.metrics[1:nLoc(x),]
  # df <- data.frame(CloneID=unique(b[duplicated(b)]), freq=as.numeric(table(b)[table(b)>1]))  

  nloc.with.secondaries <- table(duplicated(b))[2]
  if (!is.na(nloc.with.secondaries)){
    par(mfrow = c(2, 1),pty="m") 
    if (plot) {
      barplot(table(as.numeric(table(b))),col="red", space=0, main="Secondaries")
    }
    if (smearplot){
      glPlot(x)
    }
  } else {
      if (plot) {cat("  Warning: No loci with secondaries, no plot produced\n") }
  }
  
# Identify secondaries in the genlight object
  cat("Total number of SNP loci:",nLoc(x),"\n")
  if (is.na(table(duplicated(b))[2])) {
    cat("   Number of secondaries: 0 \n")
  } else {
    cat("   Number of secondaries:",table(duplicated(b))[2],"\n")
  }  
  cat("   Number of loci if secondaries are removed:",table(duplicated(b))[1],"\n")
  cat("   Returning a genlight object containing only those loci with secondaries (multiple entries per locus)\n\n")

    return(x.secondaries)
  
}  
