#' Recalculate locus metrics when individuals or populations are deleted from a genlight {adegenet\} object
#'
#' When individuals are deleted from a genlight object generated by DArT, the locus metrics no longer
#' apply. For example, the Call Rate may be different considering the subset of individuals, compared
#' with the full set. This script recalculates those affected locus metrics, namely, avgPIC, CallRate,
#' freqHets, freqHomRef, freqHomSnp, OneRatioRef, OneRatioSnp, PICRef and PICSnp. Metrics that remain
#' unaltered are RepAvg and TrimmedSeq as they are unaffected by the removal of individuals.
#' 
#' The script optionally removes resultant monomorphic loci or loci
#' with all values missing and deletes them (using gl.filter.monomorphs.r). 
#' 
#' The script returns a genlight object with the recalculated locus metadata.
#'
#' @param x -- name of the genlight object containing SNP genotypes [required]
#' @param mono.rm -- Remove monomorphic loci [default TRUE]
#' @param v -- verbosity: 0, silent; 1, brief; 2, verbose [default 1]
#' @return A genlight object with the recalculated locus metadata
#' @export
#' @author Arthur Georges (glbugs@@aerg.canberra.edu.au)
#' @examples
#' \dontrun{
#'    gl <- gl.recalc.metrics(testset.gl, mono.rm=TRUE, v=2)
#' }
#' @seealso \code{\link{gl.filter.monomorphs}}


gl.recalc.metrics <- function(x, mono.rm=FALSE, v=1){

# Recalculate statistics
  x <- utils.recalc.avgpic(x,v=v)
  x <- utils.recalc.callrate(x,v=v)
  x <- utils.recalc.freqhets(x,v=v)
  x <- utils.recalc.freqhomref(x,v=v)
  x <- utils.recalc.freqhomsnp(x,v=v)
  
# Optionally remove resultant monomorphic loci
  if (mono.rm) {x <- gl.filter.monomorphs(x,v=0)}
  
  if (v>0) {  
    cat("Note: Locus metrics recalculated\n")
    if (!mono.rm) {
      cat("note: Resultant monomorphic loci not deleted\n")
    } else {
      cat("note: Resultant monomorphic loci deleted\n")
    }
  }
  
  return <- x
  
}  
